### ISSUE TITLE
[Bug]: Paste and match style shortcut broken

### ISSUE THREAD

**Issue by davidszotten** [cutbox/CutBox#121]
### What happened?

Since i installed CutBox the global shortcut for "paste and match style" (cmd-shift-v) is broken for me. I changed the cutbox invocation shortcut to something else but i now still can't paste and match style in rich text fields

### Version

1.5.1

### What kind of Mac are you using?

M1 (not currently supported)

### What version of MacOS are you seeing the problem on?

12.x Monterey

**Comment by jasonm23** [comment]
Pasting with matching style is not a feature in cutbox.  Nor was it previously

**Comment by davidszotten** [comment]
I'm sorry if I was unclear. I'm not suggesting that this is a feature of CutBox. It's a builtin feature of osx. I'm wondering if the way CutBox installs its hotkey is somehow interfering/overriding the system feature

**Comment by jasonm23** [comment]
Yes it will default to Cmd Shift V and that will not be mapped to any other setting or app 

Simply change the cutbox shortcut to something else

**Comment by davidszotten** [comment]
I _have changed the shortcut to something else, and the new shortcut opens outbox. The bug I'm trying to report is that even after this change, the original (macOS default) behaviour of the _original shortcut still isn't working even after changing the cutbox shortcut, so I'm wondering if maybe cutbox isn't correctly unregistering or something

**Comment by jasonm23** [comment]
If you reboot Macos after making the shortcut change you are guaranteed to have no interference from cutbox as it's session will never know about the original shortcut
