### ISSUE TITLE
Favorites

### ISSUE THREAD

**Issue by jasonm23** [cutbox/CutBox#36]
Favorites are items you have copied that you want to use more often, they survive clear and remove operations.

- [x] Modify structure of cutbox history items so that they are objects `(value: String. isFavorite: Bool)`
- [x] Migrate defaults array of strings to new format on start up
- [x] Users can set an item as favorite
- [x] Users can un-set a favorite item
- [x] option to only show favorites <kbd>Cmd</kbd>+<kbd>F</kbd>
- [x] display a visual indicator on favorites (background)

Add new issues to encourage small commits. :D

**Comment by jasonm23** [comment]
### Removing an item from favorites

Two methods:

- Pure keyboard
    - [ ] pressing <kbd>Cmd</kbd> + <kbd>f</kbd> marks the current selected favorite(s) item(s) as normal items.

- Mouse keyboard
    - [ ] right click the mouse and select **"Add to favorites"**

**Comment by jasonm23** [comment]
Delivering alpha version of this feature in 1.0.47

**Comment by jasonm23** [comment]
@adellhk - interested in your feedback on this. Personally I still have trouble seeing the value in this feature.

**Comment by jasonm23** [comment]
Maybe changes / design ideas for the way the feature is presented / used.

**Comment by adellhk** [comment]
Yes, I like it and use it! I keep my employer's userId in favorites for adding to experiment APIs or doing lookups for. I'm not really sure what else I would use it for--if I did more server work I would probably save testing account userId or OAuth tokens

**Comment by jasonm23** [comment]
Cool, I'm caught up in how the UI looks and wanting to avoid clutter.

Quick side note, I'm going to change the UI so that the Magnifier on the top is what changes / is clickable.

**Comment by adellhk** [comment]
cool, seems more intuitive than secondary click on the list item!

**Comment by jasonm23** [comment]
https://gitter.im/CutBox/NewFeatures
