### ISSUE TITLE
[enhancement]Favorites or searchable captions for frequently used long strings (like tokens, user Ids)

### ISSUE THREAD

**Issue by adellhk** [cutbox/CutBox#44]
To better retrieve something like an oauth token or a userId used frequently but not constantly :)

- [x] Can be shown quickly by switching to "view favorites only" mode
- [x] Can be made/unmade as a favorite:
    - [x] by right click menu
    - [ ] opt click (would show a heart / star to be clicked)
- [ ] shown in the history with a heart / star
- [ ] Resists clear history

**Comment by adellhk** [comment]
Oh, I see that you shelved this https://github.com/ocodo/CutBox/issues/36. Maybe count one vote for unshelving or for captioning
Also, I don't think I can modify an issue's labels ie. to label this an enhancement request since I'm not a contributor?

**Comment by jasonm23** [comment]
Hi @adellhk Thanks for the interest, tbh the only reason I shelved the other issue was to avoid making the app overly complicated.

The highlights of the favorite feature design I had in mind were:

- [ ] Resists clear history
- [ ] Can be shown quickly by switching to "view favorites only" mode
- [ ] Can be made/unmade as a favorite:
    - [ ] by right click menu
    - [ ] opt click (would show a heart / star to be clicked)
- [ ] shown in the history with a heart / star

If you have any other ideas please let me know, BTW I think tagging favorites could be a nice add-on after favorites are in place.

**Comment by adellhk** [comment]
Incredible. These are all things I would use and enjoy.

**Comment by jasonm23** [comment]
Let's consider tagging another feature separate from favorites.  It'll be easier to manage as a separate thread.

I'm really interested If you have ideas around how you'd use tags.  Especially if you have ideas for step by step user flows. 

Question marks show up for me when I think about:

- [ ] how do I add a tag, what does that look and feel like?
- [ ] how do I use a tag?
- [ ] how do I manage tags (rename, remove, remove all tagged items, remove a tag without removing items..

A long list of things like this tend to explode out of my head so, if you can help me put some lines around the feature that'd be awesome.

**Comment by jasonm23** [comment]
Tagging is in #45

**Comment by jasonm23** [comment]
#active -

**Comment by jasonm23** [comment]
Reopening #36 - closing this
