### ISSUE TITLE
Tagging items

### ISSUE THREAD

**Issue by jasonm23** [cutbox/CutBox#45]
@adellhk writes:

> The tagging provides a lot of utility to me, personally. Sometimes I want the userId or OAuth token for my employee account, my personal account, or my test account. I would enjoy being able to label the things in my favorites to easily discern between similar (but different) super long strings (like oauth tokens).

**Comment by adellhk** [comment]
some potential uses:
- [ ] how do I add a tag, what does that look and feel like?
  + After selecting an item in CutBox History, maybe a badge or button leads to an additional UI element like an editable textbox that allows naming/renaming a tag
- [ ] how do I use a tag?
  + find tags via the search bar, currently captioned "Search CutBox History" -> "Search CutBox History & Tags"
- [ ] how do I manage tags (rename, remove, remove all tagged items, remove a tag without removing items..
  + the same additional UI form that allows setting the text for the tag

**Comment by jasonm23** [comment]
Testing github / gitter webhook.
