### ISSUE TITLE
[bug] paste on select / enter - not working.

### ISSUE THREAD

**Issue by adellhk** [cutbox/CutBox#47]
90% of the time when I search my cutbox history and select something, my very next action will be to return to my previous window and paste it immediately (this is something from FlyCut). Would it be possible to automate this action (and save two keystrokes 😄) and always paste the selected clipboard item after selecting it from the cutbox window with `enter`?

**Repro**
1. Select a text input field
2. Open CutBox with ⌘⇧K
3. Select a clipboard item with enter

**Expected**
 * selected CutBox history item pasted into text input field

**Actual**
* CutBox item added to clipboard & sometimes (in chrome, but not Sublime) chime sound

**Additional Details**
* [video](https://cl.ly/192g1Q1R2u1B)
* I use dvorak and CloudApp (which automatically writes new text to clipboard)
* This behavior works in the same environment if I use flycut (flycut is not running in the repro video).

**Comment by jasonm23** [comment]
Hi @adellk 

Please describe the action very precisely.  The way I'm reading your post above, it sounds like this is what CutBox already does.

I find the template below quite useful...

#### Issue description



#### Steps to reproduce the issue

1.  
2. 
3. 


#### What's the expected result?

-


#### What's the actual result?

-


#### Additional details / screenshot

- ![Screenshot]()
-

**Comment by adellhk** [comment]
Updated the original description with issue description!

**Comment by jasonm23** [comment]
Thanks!, so turns out what you're describing is a bug, and the behavior of CutBox as intended.

If you clean the environment of the other apps which write text to the clipboard, does it work?

**Comment by jasonm23** [comment]
Just to clarify: @adellhk 

> 90% of the time when I search my cutbox history and select something, my very next action will be to return to my previous window and paste it immediately (this is something from FlyCut)

This is the first principle behavior of CutBox, and should always work.

FYI Here's how it is done in [FlyCut](https://github.com/TermiT/Flycut/blob/cadc7606c9830a2d9b8a2bc76b90a5bc1f069689/AppController.m#L709-L731) (ObjC) and here's how I do it in [CutBox](https://github.com/cutbox/CutBox/blob/846801107c4e2010fc1b96622b1b806b2c4810fc/CutBox/CutBox/Source/Utilities/FakeKeyEvents.swift) (Swift 4)

So far I've not been able to reproduce this problem.

- In Chrome I can use CutBox to paste to anywhere my text cursor is (tried with TextArea. Input fields and Address bar)
- In all other apps I've tried so far. (Terminal, iTerm, Emacs, XCode, TextEditor, Finder, TextMate, Atom, VSCode, Excel, Word, Mail.app, etc. etc.)
- I haven't tried SublimeText, I'll download it now and give it a shot.

**Comment by jasonm23** [comment]
Tried with SublimeText  https://vimeo.com/267360278

**Comment by jasonm23** [comment]
I assume if you're using Dvorak <kbd>Cmd</kbd>+<kbd>v</kbd> pastes normally.  

If not let me know what does activate paste.  I'm not seeing anything in FlyCut that compensates for this though.

**Comment by adellhk** [comment]
Sorry about the slow response. It's something to do with Dvorak--if I change my keyboard back to US, then the CutBox default behavior works, but when in Dvorak I just get a bell/error sound. For whatever reason FlyCut works in both Dvorak and US though.

**Comment by jasonm23** [comment]
@adellhk - what's the Paste key combo when you use DVorak?

**Comment by jasonm23** [comment]
https://github.com/TermiT/Flycut/issues/53

**Comment by adellhk** [comment]
it's still cmd + v, but dvorak "v" maps to qwerty "."/">" and qwerty "v" maps to dvorak "k". It looks like this change fixed it in flycut https://github.com/TermiT/Flycut/commit/0b79c1fafd5e2b8f60355954e0def3b689444ea4

**Comment by jasonm23** [comment]
Ok, it looks like Command V is used as paste on DVorak, but because it's in a different place, the keycode is different.

... oh ok you saw it too.

I'll need to do a reverse transform on the key code as FlyCut does, I'll get this done in a few mins.

**Comment by adellhk** [comment]
Thanks for making this!!! I need to leave you for now (sleep)--not that I have done anything you wouldn't have done on your own--but I look forward to using this at work tomorrow or in the future! 💮

**Comment by jasonm23** [comment]
f8f930374441f97b29bfd71a4e12ecd73253029c

**Comment by adellhk** [comment]
It's still not working for me :/

**Comment by jasonm23** [comment]
Thanks for verifying.

**Comment by jasonm23** [comment]
Ok I think it's the right approach but I'm doing something wrong. 

I'll look again

**Comment by jasonm23** [comment]
1.0.45 solves this.

**Comment by adellhk** [comment]
Yes! It does!

**Comment by jasonm23** [comment]
FYI 1.0.44 was not failing because I coded the solution wrong.

No, it was  because I was still directly trying to fake keycode `0x09` (i.e. US ANSI keycode for `V`) 

All the new code translates a single char (in our case `"V"`) to whatever it's hardware key code currently is.

In a hilarious act of stupidity, I didn't check that before completely re-implementing the translation code.

On the bright side the string to key code transformation code is better (I was generating a fake event for each char first time around.)

Here's the diff... https://github.com/cutbox/CutBox/commit/dadf6dfebdb33666e083ccc096b746e5fef3c604

**Comment by adellhk** [comment]
I only know java/kotlin/android so this Swift & keycode business is all Greek to me, but I shared this project with a coworker bc I'm super stoked on how effective you've been and we're both shocked by how effective you are! 💪 😮 😍
