### ISSUE TITLE
[bug] keep cutbox window on main display

### ISSUE THREAD

**Issue by adellhk** [cutbox/CutBox#48]
[picture of malformed cutbox on secondary display](https://cl.ly/2Q4430401G1l/[011b53332af17615bc01878f4b889916]_IMG_20180430_144650.jpg)

**Comment by jasonm23** [comment]
Thanks for the picture, I'll see if I can reproduce it.

Are there any steps to reproduce that I need to follow? 

E.g. which display has the menu bar?

**Comment by jasonm23** [comment]
Actually I was surprised that you got CutBox to appear on the secondary display.

It specifically uses main screen to size and position itself.

I'm going to close this bug, but I'll start a new enhancement issue

**Comment by jasonm23** [comment]
#49
