### ISSUE TITLE
Alternative storage options (text)

### ISSUE THREAD

**Issue by jasonm23** [cutbox/CutBox#72]
Profile 

- [ ] SQLLite
- [ ] JSON using high performance options
- [ ] others...

**Comment by bwDialogs** [comment]
Would love to have **encrypted-at-rest** storage.

**Comment by jasonm23** [comment]
@bwDialogs - maybe just use macOS full disk encryption? (should be default from El Cap onwards.)

**Comment by jasonm23** [comment]
closing.
