### ISSUE TITLE
Improper search box placement on internal display when not configured as main display (2 displays setup)

### ISSUE THREAD

**Issue by ddacunha** [cutbox/CutBox#73]
Hello,
I have two screens setup on a MacBook Pro (15-inch, Late 2016), the second screen is  **DELL U2718Q 4K configured as the main display**. 

The search box appears too low on the internal display when it's not configured as the main display (relocate menu bar to external display in System Preferences/Display).

Here are screenshots of the internal display:
<img width="1440" alt="fullscreen_4_6_18__18_44" src="https://user-images.githubusercontent.com/271673/40913657-d84c2334-6827-11e8-804a-68b4523521a9.png">
<img width="1440" alt="fullscreen_4_6_18__18_45-2" src="https://user-images.githubusercontent.com/271673/40913658-d87950f2-6827-11e8-9aa4-ffdf4c24df4e.png">
<img width="1440" alt="fullscreen_4_6_18__18_45" src="https://user-images.githubusercontent.com/271673/40913659-d8a45fae-6827-11e8-85f5-c65b53f172eb.png">

**Note that there are no issues when the internal screen is set up as the main display.**

**Comment by jasonm23** [comment]
@ddacunha - Thank you for the bug report. I'll do some further tests and get it fixed.

**Comment by jasonm23** [comment]
Verifying some cases.

1. When the secondary display is the internal display and it is placed above the primary display (1 additional attached display.) CutBox appears as expected in both displays.

<img width="780" alt="screen shot 2018-06-05 at 9 54 18 am" src="https://user-images.githubusercontent.com/71587/40950713-720b8554-68a6-11e8-9268-eabf309d1c43.png">

- - -

In all the scenarios below CutBox doesn't appear, the common denominator is the Y position of the secondary display (as internal) is higher than the primary display ()

<img width="780" alt="screen shot 2018-06-05 at 9 53 43 am" src="https://user-images.githubusercontent.com/71587/40950714-72337e38-68a6-11e8-8ad0-14b1a6dd63c8.png">

<img width="780" alt="screen shot 2018-06-05 at 9 53 34 am" src="https://user-images.githubusercontent.com/71587/40950715-725f7a56-68a6-11e8-929d-6238bd01b840.png">

<img width="780" alt="screen shot 2018-06-05 at 9 53 21 am" src="https://user-images.githubusercontent.com/71587/40950717-728af82a-68a6-11e8-97c7-b421b11ea001.png">

<img width="780" alt="screen shot 2018-06-05 at 9 53 05 am" src="https://user-images.githubusercontent.com/71587/40950718-72b599e0-68a6-11e8-9680-0b66bf7a3fa6.png">

**Comment by ddacunha** [comment]
I have tested all the scenarios above and have the same results.

**Comment by jasonm23** [comment]
Verifying cases where the internal display is primary and attached is secondary.

![](https://user-images.githubusercontent.com/71587/40950939-76d208e6-68a7-11e8-8819-55b9dc2a4184.png)

![screen shot 2018-06-05 at 10 00 48 am 2](https://user-images.githubusercontent.com/71587/40950919-56949eae-68a7-11e8-82a8-4b5c1284a4de.png)

Similar problem regardless of which screen is the primary.

Mapping of the Y axis over multiple screens, may be difficult to determine.  Currently I'm just using the NSScreen which is in the same position as the mouse and using it's reported frame.

**Comment by jasonm23** [comment]
Relevant: https://stackoverflow.com/a/14779155/311660

**Comment by jasonm23** [comment]
In a nutshell (and in case that stackoverflow link fades away.) 

Undocumented in the macOS developer docs.:

On MacOS the primary screen sets the global coordinate space of screens and it's bottom left is `{x:0, y:0}`

**Comment by jasonm23** [comment]
![image](https://user-images.githubusercontent.com/71587/41014616-52f3a270-697b-11e8-8568-11797a2cf662.png)

**Comment by jasonm23** [comment]
Fake screen data.

```
x: 0.0      y: 0.0      w: 1280.0   h: 800.0    (primary: true)
x: 1280.0   y: -640.0   w: 2560.0   h: 1440.0   (primary: false)
```

**Comment by jasonm23** [comment]
Fixed really! .. v1.3.13
