### ISSUE TITLE
Provide brew package

### ISSUE THREAD

**Issue by AtibaBryan** [cutbox/CutBox#78]
As somebody that's lazy about software upgrades/installs I'd massively appreciate a brew cask for this.

**Comment by hirocaster** [comment]
https://github.com/Homebrew/homebrew-cask/pull/55593

**Comment by jasonm23** [comment]
You can try this again as there are now more than 50 stars

**Comment by DwordPtr** [comment]
Please do I miss inline search in my clipboard.

**Comment by jasonm23** [comment]
Cask now had 1.4.3 

Tests are all green. Sorry about the breakages.
