### ISSUE TITLE
Could not load cutbox.js

### ISSUE THREAD

**Issue by akapitoha** [cutbox/CutBox#80]
Hello,
after install and on each start I get
`Could not load ~/.cutbox.js. File does not exist`
There's an item in menu to reload it, but it doesn't help.

Version: 1.3.13 (9996)
mac os mojave.

**Comment by jasonm23** [comment]
Do you have a .cutbox.js file?

**Comment by akapitoha** [comment]
My bad, sorry

**Comment by jasonm23** [comment]
No problem.

To be honest I think the error message could be better worded.

>
