### ISSUE TITLE
History limit preference resets on app restart

### ISSUE THREAD

**Issue by akapitoha** [cutbox/CutBox#81]
Version: 1.3.13 (9996)
mac os mojave

1. Start cutbox
2. Open preferences
3. Changes settings in General tab
4. Go to Advanced
5. Uncheck "Unlimited" and set history limit
6. Close preferences dialog
7. Open preferences again -> all changes are still there
8. Quit the app
9. Start cutbox and open preferences -> History limit is set to "Unlimited" again, other changes were saved

**Comment by jasonm23** [comment]
Thanks for the heads up.

I'll investigate at the weekend.

**Comment by jasonm23** [comment]
Worked on a fix with @suyashnene - will be testing and publishing at the next opportunity

**Comment by jasonm23** [comment]
ref: #82
