### ISSUE TITLE
MacOS code signature validation failed fatally

### ISSUE THREAD

**Issue by slionelr** [cutbox/CutBox#83]
#### Issue description
Code signature is invalid an prevents from CutBox to start on MacOS.

#### Steps to reproduce the issue
1. Install the latest CutBox on MacOS 10.14.4
2. Copy CutBox.app into Application folder
3. Open CutBox

#### What's the expected result?
- The app should open up

#### What's the actual result?
- The application does not start
- sudo dmesg shows: "mac_vnode_check_signature: /Applications/CutBox.app/Contents/MacOS/CutBox: code signature validation failed fatally: When validating /Applications/CutBox.app/Contents/MacOS/CutBox:
  The code contains a Team ID, but validating its signature failed.
Please check your system log.proc 1603: load code signature error 4 for file "CutBox" "

#### Additional details / screenshot
- ![image](https://user-images.githubusercontent.com/2429254/55311183-ee224280-546a-11e9-9d3d-f2d4f44ad764.png)

**Comment by jasonm23** [comment]
Thank you.  A new release will be cut today

**Comment by jasonm23** [comment]
Fixed in 1.3.13 - https://github.com/cutbox/CutBox/releases

Note:  TODO sparkle release for autoupdates.

**Comment by jasonm23** [comment]
https://github.com/cutbox/CutBox/releases/tag/1.4.0

**Comment by jasonm23** [comment]
Problem when testing this release on another mac. - investigating.

**Comment by jasonm23** [comment]
# NOTE

It seems that a hardened app bundle is required for Gatekeeper on Mojave.  

# Solution

I will need to upgrade cutbox to work with XCode 10, which will take a few man hours that are quite scarce for me at the moment.

**I recommend that you build cutbox yourself in the meantime.  Watch this issue for the official build update.**

**Comment by jasonm23** [comment]
If you fix CutBox dependency on XCode 10.1 please submit a pull request.  Thank you.

**Comment by jasonm23** [comment]
https://github.com/cutbox/CutBox/releases/tag/1.4.1

**Comment by jasonm23** [comment]
Tests ok on 2 macs which were failing with this error.

**Comment by jasonm23** [comment]
1.4.2 latest
