### ISSUE TITLE
App quits after opening search via global hotkey

### ISSUE THREAD

**Issue by akapitoha** [cutbox/CutBox#84]
Hi
I updated to 1.4.0 - the app wasn't starting at all.
Same with fresh install

Then updated to 1.4.1
Started the app
Open search via global hotkey -> and app quits

Mojave 10.14.2

**Comment by jasonm23** [comment]
Thanks for the bug report

**Comment by jasonm23** [comment]
Reproduced 

Side note: Seems to be ok if I activate the status menu first.  (not a solution!!)

**Comment by jasonm23** [comment]
`Could not connect action, target class CutBox.SearchAndPreviewView does not respond to -clickIcon:`

**Comment by jasonm23** [comment]
Fixed partially in 1.4.2 however still crashed.

**Comment by jasonm23** [comment]
App crashes reading modifers event in HotKeyCenter : e.g.

    0   com.clipy-app.Magnet          	0x000000010abf1c93 HotKeyCenter.sendModifiersEvent(_:) + 691 (HotKeyCenter.swift:169)

**Comment by Eymantia** [comment]
Quits as soon as I hit Command+Option. However, for some reason, restarting [Magnet](http://magnet.crowdcafe.com) fixed it for me. Maybe some sort of global hotkey conflict between the two?

**Comment by jasonm23** [comment]
I expect it to quit as soon as you tap Cmd.

The problem is magnet, specifically it's the HotKeyCenter dependency of Magnet. (Which CutBox depends on)

**Comment by jasonm23** [comment]
- [ ] TODO set up a quick test app to isolate the issue.

**Comment by jasonm23** [comment]
Updated all dependency on Clipy: Magnet & Keyholder

Tests pass

CMD key event no longer crashes Cutbox.

🥇 

Released:

# 1.4.3

@akapitoha  thanks for your patience
