### ISSUE TITLE
Search and preview are quite slow

### ISSUE THREAD

**Issue by dstd** [cutbox/CutBox#85]
Implementation of delegate of NSTableView is quite non-optimal. `tableView(_:viewFor:row:)` uses HistoryService's `dict`, which is computed property. So every row it re-creates a collection over and over again.

While it's not that noticeable when the filter is empty, all becomes quite laggy when one is typing a text to filter or scrolling a filtered list.

I believe it's better to cache items somewhere – either in `SearchViewController`, or in `HistoryService`. So it will be O(n) instead of O(n^2).

I made a quick-fix with caching in HistoryService, but not sure if it is a best way: https://github.com/cutbox/CutBox/compare/master...dstd:improve-speedup

**Comment by jasonm23** [comment]
Thanks for the heads up.  Let's consider caching a good next step.  It's not necessary to perfect it as a trade off against improvement.

Can you add some tests and create a pull request?

**Comment by jasonm23** [comment]
I see you already added a spec! Nice work 👍

**Comment by jasonm23** [comment]
Closing for now.
