### ISSUE TITLE
superfluous backtick in js example

### ISSUE THREAD

**Issue by bahnfrei** [cutbox/CutBox#88]
you may want to remove the backtick in the javascript example file ~/.cutbox/basic.js (https://github.com/cutbox/CutBox/wiki/Javascript-Examples)

```
var stripTags = i => join(i).replace(/<[^>]*>/gm, "");`
```

vs.

```
var stripTags = i => join(i).replace(/<[^>]*>/gm, "");
```

**Comment by jasonm23** [comment]
Thank you for the heads up

**Comment by jasonm23** [comment]
Fixed
