### ISSUE TITLE
Failure to launch on fresh install

### ISSUE THREAD

**Issue by C-Saunders** [cutbox/CutBox#89]
I apologize for this generic custom support bug report, but I'm not sure what to do next.

I was having an issue for a while where typing certain characters into the search box would cause the app to crash (I know Q and R, but they may have been others. I restarted my computer, but that didn't fix the issue, so I tried reinstalling the application.

I think the Q and R issue started after I installed an update earlier this week last week.

I have now tried reinstalling the application three or four times, restarting my computer, and deleting `~/Library/Preferences/info.ocodo.CutBox.plist`, but it will not launch.

Any advice or next steps?

Thanks!

**Comment by jasonm23** [comment]
If you download 1.4.3 and replace the upgrade & restart do you still have the problem?

Check the About box for version 1.4.3 after you down grade

**Comment by C-Saunders** [comment]
I installed 8c4f9b5 (1.4.3) and restarted my computer, but it still refuses to launch and doesn't show any sort of error that I can see.

I'm not sure what the About box is, but here is the info from the OS:
<img width="261" alt="Screen Shot 2019-08-14 at 9 45 30 PM" src="https://user-images.githubusercontent.com/1126917/63067420-ed032680-bedc-11e9-96b1-c3e68f68a614.png">

I checked the OS console and saw "Saved crash report for CutBox[744] version ??? to CutBox_2019-08-14-214745_STT-MLT02.crash". Here is the content:

```
Process:               CutBox [744]
Path:                  /Applications/CutBox.app/Contents/MacOS/CutBox
Identifier:            info.ocodo.CutBox
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           CutBox [744]
User ID:               502

Date/Time:             2019-08-14 21:47:45.068 -0400
OS Version:            Mac OS X 10.14.6 (18G87)
Report Version:        12
Bridge OS Version:     3.6 (16P6568)
Anonymous UUID:        956D601F-B563-A319-5C62-F2F30AB03239


Time Awake Since Boot: 370 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x1

kernel messages:

VM Regions Near 0 (cr2):
--> 
    __TEXT                 000000010b68b000-000000010b6f0000 [  404K] r-x/rwx SM=COW  

Thread 0 Crashed:
0                                 	0x0000000112e15000 _dyld_start + 0

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x00007ffee4574bb0
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
  rip: 0x0000000112e15000  rfl: 0x0000000000000200  cr2: 0x0000000000000000
  
Logical CPU:     0
Error Code:      0x00000000
Trap Number:     0


Binary Images:
       0x10b68b000 -        0x10b6efff7 + (0) <FEDC5470-AA53-3328-A2DB-028483E9B4FA> 
       0x112e14000 -        0x112e7e6ef + (655.1.1) <D3E77331-ACE5-349D-A7CC-433D626D4A5B> 

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 113
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=1064K resident=0K(0%) swapped_out_or_unallocated=1064K(100%)
Writable regions: Total=8412K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=8412K(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        1 
Stack                             8192K        1 
__DATA                             316K        4 
__LINKEDIT                         232K        2 
__TEXT                             832K        2 
shared memory                        8K        2 
===========                     =======  ======= 
TOTAL                             65.4M       12 
```

I also had a couple CutBoxHelper crash logs:
```
Process:               CutBoxHelper [494]
Path:                  /Applications/CutBox.app/Contents/Library/LoginItems/CutBoxHelper.app/Contents/MacOS/CutBoxHelper
Identifier:            CutBoxHelper
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           CutBoxHelper [494]
User ID:               502

Date/Time:             2019-08-14 15:18:32.524 -0400
OS Version:            Mac OS X 10.14.6 (18G87)
Report Version:        12
Bridge OS Version:     3.6 (16P6568)
Anonymous UUID:        956D601F-B563-A319-5C62-F2F30AB03239


Time Awake Since Boot: 56 seconds

System Integrity Protection: enabled

Crashed Thread:        Unknown

Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x1

kernel messages:

Backtrace not available

Unknown thread crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x00007ffeeb299c20
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
  rip: 0x0000000113902000  rfl: 0x0000000000000200  cr2: 0x0000000000000000
  
Logical CPU:     0
Error Code:      0x00000000
Trap Number:     0


Binary images description not available


External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 106
    thread_create: 0
    thread_set_state: 0
```

So maybe it has something to do with code signing? Perhaps related to the most recent MacOS update? I am running Mojave 10.14.6 (18G87).

Please let me know what else you need. Thanks so much for your help!

**Comment by jasonm23** [comment]
Which Macos version are you using?

I'm not currently supporting the new Beta of Catalina.

**Comment by jasonm23** [comment]
Sorry. I see you are using Mojave.

1.4.3 was released to fix signing issues in Mojave.

1.4.4 provides some storage optimization of the history when it gets large.

**Comment by jasonm23** [comment]
Unable to reproduce at this time.

**Comment by awreccan** [comment]
+1. I'm on Mojave 10.14.5. Cutbox suddenly stopped launching. I tried a reinstall and it still won't launch.

**Comment by jasonm23** [comment]
CutBox version @awreccan?

**Comment by jasonm23** [comment]
Do attempt revert to CutBox 1.4.3 as part of troubleshooting

**Comment by awreccan** [comment]
@jasonm23 Just reinstalled from https://github.com/cutbox/CutBox/releases/tag/1.4.3, still unable to launch. I haven't tried deleting ~/Library/... etc though.

**Comment by jasonm23** [comment]
Will need to clean up the preferences in ~/Library I think we may need to pull the 1.4.4 upgrade, as migration of the store might be causing the issue.

**Comment by jasonm23** [comment]
@awreccan if you could post the preferences path here as I'm on mobile phone right now, without access to my MacBook for 5hrs+-

**Comment by awreccan** [comment]
@jasonm23 no worries, it's not urgent. If you could provide a set of instructions on how to get back up and running when you have a computer, that'd be great.

I do have `~/Library/Preferences/info.ocodo.CutBox.plist` like @C-Saunders. I'm assuming that's the preferences file.

**Comment by jasonm23** [comment]
Thank you, that's the correct plist.

My working (unconfirmed) assumption is that the optimizations to history
subsystem may not be backwards compatible therefore rollback to 1.4.3 might
be unable to use a 1.4.4 store. Similarly 1.4.4 may be thrown by history
stores from older versions.

Personally I've managed to upgrade from 1.4.3 to 1.4.4 on Mojave myself,
however I didn't author the history optimization and so more can be done to
review possible issues with history store migration.

**Comment by jasonm23** [comment]
Ok nothing so complicated.

Turns out the latest update of Mojave breaks signing.  So I'll cut another
release as 1.4.5 which is built against Mojave 10.14.6

ETA 20 mins

**Comment by jasonm23** [comment]
https://github.com/cutbox/CutBox/releases/tag/1.4.5 fixed

**Comment by jasonm23** [comment]
Please let me know if this is working for you.  I wasn't able to update using the built in updater and had to download and install again.

After updating Mojave, my 1.4.4 failed to open with the "improper signing" error in Console.app

Now passes the "Works for me!" test

**Comment by C-Saunders** [comment]
@jasonm23 works for me, too! Thank you!!

**Comment by jasonm23** [comment]
@C-Saunders cool 💃

**Comment by awreccan** [comment]
Works for me too, thanks! 😄
