### ISSUE TITLE
Crash after typing anything that matches more than 2 letters in fuzzy search

### ISSUE THREAD

**Issue by ulfgj** [cutbox/CutBox#90]
#### Issue description
Crash after typing anything that matches more than 2 letters in fuzzy search

#### Steps to reproduce the issue

1.
2.
3.

#### What's the expected result?

-

#### What's the actual result?

-

#### Additional details / screenshot

- ![Screenshot]()
-

**Comment by jasonm23** [comment]
Hi @ulfgi could you make sure you:

1. Provide the CutBox version used (CutBox menu > About)
2. Macos version & build (About this Mac)
3. Clear your current history and try again
3.

**Comment by ulfgj** [comment]
hi!
clearing the history worked, but the issue reappeared after a couple of
uses.
older versions (tried 1.4.3 & 1.4.4) won't start at all.

CutBox 1.4.5
Mojave 10.14.6 (18G87)
MacBook Pro (Retina, 15-inch, Mid 2014)

2,2 GHz Intel Core i7
16 GB 1600 MHz DDR3

Intel Iris Pro 1536 MB

**Comment by jasonm23** [comment]
See #89 as to why older versions won't work.

I'll try and see if I can reproduce the problem

**Comment by jasonm23** [comment]
Unable to reproduce, leaving open for more info and other users to report same issue

**Comment by jasonm23** [comment]
If it's safe to do so, attach `~/Library/Preferences/info.ocodo.CutBox.plist` (ensure there is no personal info, passwords etc.)

**Comment by ulfgj** [comment]
cool. i cleaned the history. i'll provide the file when it crashes again.

**Comment by ulfgj** [comment]
attached is an example of a plist that causes a crashwhen i'm typing "en"
in the fuzzy search.
about 30 items currently in this history. limit set to 140.

**Comment by jasonm23** [comment]
You'll need to attach via the GitHub interface

**Comment by ulfgj** [comment]
tnx. my post has been edited and file attached.

**Comment by awreccan** [comment]
me too

**Comment by balazser** [comment]
Unfortunately also crashes on my computer.

macOs Mojave 10.14.6 (18G87)
version: 1.4.5 (10219)

**Comment by ulfgj** [comment]
temp fix:
- set all stuff u need as favourites
- clear history now and then

**Comment by gonzalt03** [comment]
Me too.

macOS Mojave 10.14.6 (18G95)
version: 1.4.5 (10219)

**Comment by jasonm23** [comment]
My apologies for not solving this yet.  I haven't had any time to devote to CutBox maintenance for a while.

Writing this to remind myself to set aside time this coming week.

**Comment by jasonm23** [comment]
Btw @ulfgj that plist.txt file.  Is that untouched?

**Comment by ulfgj** [comment]
> Btw @ulfgj that plist.txt file. Is that untouched?

dunno if i know what that means... :/
i believe i edited away a big chunk of it before posting, though.

**Comment by jasonm23** [comment]
Right, by untouched I do mean unedited.

>
I can't do a test with an edited plist.

It will have to be an unedited plist that causes CutBox to crash.

**Comment by ulfgj** [comment]
still trying to recreate a situation where it crashes, but it seems only when i copy sensitive information from freshdesk cutbox crashes. lol.

**Comment by awreccan** [comment]
I have this issue too. Would like to see it fixed soon, so is there anything I can do to help debug?

**Comment by jasonm23** [comment]
I need a completey untouched CutBox data file that can provide a reproduction of the crash.  It can be used as the fixture basis for an automated test.

**Comment by awreccan** [comment]
I'm not super familiar with MacOS. What's the file path? I can send it to you.

**Comment by jasonm23** [comment]
Path is mentioned above in this thread.

You should ensure no private / personally identifiable info is in the file (by removing entries using CutBox.)

Do check carefully!  Then attach it to a new comment on this thread.

**Comment by jasonm23** [comment]
@awreccan https://github.com/cutbox/CutBox/issues/90#issuecomment-522971279

**Comment by jasonm23** [comment]
It's important that the file is not modified directly so I can use it to reproduce the crash.

If you have to remove any entries, only do that using CutBox itself, don't edit the file in a text editor.

After removing entries, double check the issue still occurs.

**Comment by awreccan** [comment]
Gotcha. I had too much sensitive info so I cleared history and now the issue isn't occurring. I suspect it has to do with certain characters in history or a certain number of items in history. Will use as per normal and keep trying fuzzy search, and hopefully come across the bug again.

**Comment by jasonm23** [comment]
>  I suspect it has to do with certain characters in history or a certain number of items in history.

Right, that's the working hypothesis, but we haven't been able to nail it down.

**Comment by ulfgj** [comment]
managed to get one with a very small sample of clips.
[info.ocodo.CutBox.plist.txt](https://github.com/cutbox/CutBox/files/3762383/info.ocodo.CutBox.plist.txt)

the issue sems to be when copying a URL from chrome that expansd afterwards to show the protocol, as seen in the attached screenshot 
![Untitled-1](https://user-images.githubusercontent.com/4105263/67393776-53728800-f5a3-11e9-9067-2a0f69ff1473.png)

**Comment by jasonm23** [comment]
Is there a reason you are adding .txt ?

**Comment by ulfgj** [comment]
yup. github didn't allow me to sen .plist files.

**Comment by jasonm23** [comment]
Ok makes sense

**Comment by awreccan** [comment]
[info.ocodo.CutBox.plist.zip](https://github.com/cutbox/CutBox/files/3770261/info.ocodo.CutBox.plist.zip)

Some ways to make Cutbox crash with this file:
- type `htt`
- type `s`

![image](https://user-images.githubusercontent.com/10543509/67541650-58a71280-f71c-11e9-8816-3a37ffd4cdf5.png)

**Comment by jasonm23** [comment]
Thanks I'll give it a try today.  Hopefully it's going to crash :+1:

**Comment by awreccan** [comment]
@jasonm23 any updates?

**Comment by awreccan** [comment]
bump

**Comment by levjad** [comment]
Any updates?

**Comment by jasonm23** [comment]
I've had no time to work on this unfortunately.

I should be able to look at it this week at some point.

**Comment by jasonm23** [comment]
Successful reproduction of crash.

**Comment by ulfgj** [comment]
yay!

**Comment by jasonm23** [comment]
Ok.  After a long wait (sorry!) - I've been looking into this again and have a few leads on it.  Unfortunately trying to reproduce in a unit test is currently failing.

The dependency I'm relying on is looking a bit dead, so I'm thinking about using an alternative fuzzy match dependency or just spinning my own, probably better to do that in the long run.

https://github.com/yichizhang/SwiftyStringScore/issues/28

**Comment by jasonm23** [comment]
Swapping out to use 8Bytes/SwiftyStringScore - works. 1.4.7 pre-release will solve it.  Please check when it's available (~10min)

**Comment by awreccan** [comment]
Works! Thank you this is awesome!

**Comment by awreccan** [comment]
One problem though ... the search is quite laggy. Wondering if you could add a debounce to the searchbar? https://levelup.gitconnected.com/debounce-in-javascript-improve-your-applications-performance-5b01855e086

**Comment by jasonm23** [comment]
@awreccan - please open that as a separate issue.  

Thanks for the feedback.
