### ISSUE TITLE
Ability to in-place edit copied scraps before pasting.

### ISSUE THREAD

**Issue by mmt050** [cutbox/CutBox#91]
Hello, 
Thanks for the amazing pasteboard, it's the best thing since sliced bread.

Many times, I catch myself copying something which I'd like to change a bit before pasting, or simply change the copied scrap permanently. My instinct is to click in the right pane and type, I think it would be awesome if this was allowed, and it seems sort-of simple to do. 

What do you think?

**Comment by jasonm23** [comment]
Thanks for the suggestion

**Comment by jasonm23** [comment]
So I had thought this would be a useful thing to have when I was first building CutBox, however when I considered the UX mechanism, it felt somewhat klunky and less intuitive than just editing the pasted text.  Note that my primary goal is to make a fast keyboard driven interaction without additional UI control buttons and clutter.

Here is a user story that describes my user flow idea, maybe we can figure out a couple of details to make it work nicely.

- - - 
> Given I want to paste an edited version of something I've copied
> When I open the CutBox popup, find my clip text, and click on it and edit my text.
> When I _press enter_ the edited clip text
> Then it will be pasted to the originally focused text control in MacOS
- - -

So this left me with a few questions:

1. _press enter_ to finish editing, seems intuitive, however, we will probably want to edit in new-lines fairly often too, so we'd need a keyboard based method to conclude editing.
    1. If we used _cmd + enter_ that would be fairly typical of many common editing set ups.
2. Once we've edited our clip text, do we  always want to keep the edited version or just use it for this paste operation?
    1. By assuming a default that the edit is always persisted, we adhere to the principal of least surprise. My reasoning is that since the user made the edit, discarding would seems like an additional step (I need this assumption validated, does it make sense?)

Let me know your thoughts on how the UX might work.

**Comment by mmt050** [comment]
Thank you very much for taking the time to consider this. 

Focusing on "keyboard-driven" since I also strongly agree with that goal, my thoughts: 
- currently Shift-Cmd-V evokes the CutBox windows, Type+Arrows to select snippet: **pressing tab currently does nothing**. _It could be used to instantly focus on the right pane ready for editing?_ (Or a combination of cmd+e?)
- **once focus is in edit pane**, Enter is used to input new-line, Cmd+enter is used to paste. If focus is not in edit pane, Enter retains its "paste" functionality.
- there should be some **GUI indication that the snippet is now "modified**". CMD+S could maybe save it, (removing the UI modified indication)? I anticipate this would be more useful than assuming Save-on-Paste. 
- **Should saved clipping produce a new clipping (instead of modifying the existing one in-place?** **My opinion is Yes**, I'd find that useful, since often happen to edit long command lines, where I'd like to keep history of commands I issued. 

Cheers,
-m

**Comment by jasonm23** [comment]
For a first try, I may just do the keyboard only interaction, so clicking the view pane does nothing.

It'll keep implementation simple and restrict support overhead to power users.

**Comment by jasonm23** [comment]
Should save as new clip is a most excellent suggestion. I'll use that.

**Comment by jasonm23** [comment]
Unfortunately I have had no time available to implement this.

Issue is open for contribution

**Comment by jasonm23** [comment]
Looking at this again. 

Just want to clarify:

1. Select item
2. Press TAB
3. Focus goes to the preview pane which is now editable.
4. Pressing Cmd-enter in the preview pane will paste and keep the edit as a new item in history.

Keyboard. interaction to begin (TAB). Taking focus out (i.e. clicking on anything else will revert the to normal preview mode (or shut the CutBox window as usual)
