### ISSUE TITLE
Mac throws warning about this software

### ISSUE THREAD

**Issue by alongouldman** [cutbox/CutBox#94]
I get this message, when trying to open this app:

![image](https://user-images.githubusercontent.com/42400390/75096923-38de0900-55ad-11ea-9b11-40cb7a5f5e3b.png)

This is strange, because this didn't happen in the past, but started now. 
I wish this will be fixed - I love this software!!

**Comment by jasonm23** [comment]
Unfortunately this is due to Apple's attempt to squeeze out people writing
software that's not distributed through the App Store.

Sad.

>

**Comment by alongouldman** [comment]
@jasonm23 Can I Ignore this somehow? Or add this to app store?

**Comment by jasonm23** [comment]
Check with Apple to see if you can ignore.

CutBox will not be on App Store in the foreseeable future.

**Comment by levjad** [comment]
Unfortunately it's happening for me too. So far, I didn't found a (working) workaround.

The only way I found was to right click on cutbox > Information > Override malware protection. But that only helped to get rid of the message. Cutbox doesn't start after that.

**Comment by alongouldman** [comment]
Exactly the same for me. I was spending all of yesterday trying to find replacement for this app, but with no luck. I hope this will be fixed sometime...

**Comment by jlongman** [comment]
console when over-riding malware protection:
```
default	11:59:50.283869-0500	lsd	Non-fatal error enumerating at <private>, continuing: Error Domain=NSCocoaErrorDomain Code=260 "The file “PlugIns” couldn’t be opened because there is no such file." UserInfo={NSURL=PlugIns/ -- file:///Applications/CutBox.app/Contents/, NSFilePath=/Applications/CutBox.app/Contents/PlugIns, NSUnderlyingError=0x7fc8fc329a00 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
default	11:59:50.284015-0500	lsd	- 45683955: Checking whether application is managed at file:///Applications/CutBox.app/info.ocodo.CutBox
default	11:59:50.305978-0500	lsd	Non-fatal error enumerating at <private>, continuing: Error Domain=NSCocoaErrorDomain Code=260 "The file “PlugIns” couldn’t be opened because there is no such file." UserInfo={NSURL=PlugIns/ -- file:///Applications/CutBox.app/Contents/Library/LoginItems/CutBoxHelper.app/Contents/, NSFilePath=/Applications/CutBox.app/Contents/Library/LoginItems/CutBoxHelper.app/Contents/PlugIns, NSUnderlyingError=0x7fc8fb628840 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
default	11:59:50.306047-0500	lsd	- 45683955: Checking whether application is managed at file:///Applications/CutBox.app/Contents/Library/LoginItems/CutBoxHelper.app//info.ocodo.CutBoxHelper
default	11:59:50.327800-0500	Finder	LAUNCHING:0x0-0x68068 CutBox foreground=0 bringForward=0 seed=237 userActivityCount=0
default	11:59:50.350507-0500	amfid	/Applications/CutBox.app/Contents/MacOS/CutBox signature not valid: -2147409652
default	11:59:50.362761-0500	kernel	mac_vnode_check_signature: /Applications/CutBox.app/Contents/MacOS/CutBox: code signature validation failed fatally: When validating /Applications/CutBox.app/Contents/MacOS/CutBox:
  The code contains a Team ID, but validating its signature failed.
Please check your system log.
default	11:59:50.362792-0500	kernel	proc 2950: load code signature error 4 for file "CutBox"
default	11:59:50.363276-0500	kernel	Security policy would not allow process: 2950, /Applications/CutBox.app/Contents/MacOS/CutBox
default	11:59:50.366189-0500	loginwindow	-[ApplicationManager checkInAppContext:eventData:] | ApplicationManager: Checked in app : CutBox
default	11:59:50.371581-0500	ReportCrash	Parsing corpse data for process CutBox [pid 2950]
default	11:59:50.371345-0500	loginwindow	-[PersistentAppsSupport applicationQuit:] | for app:CutBox, _appTrackingState = 2
default	11:59:50.415709-0500	dmd	Received xpc stream event (distributed notification matching) with name: com.apple.LaunchServices.applicationRegistered user info: {
    bundleIDs =     (
        "info.ocodo.CutBox"
    );
    isPlaceholder = 0;
}
default	11:59:50.415954-0500	dmd	Received xpc stream event (distributed notification matching) with name: com.apple.LaunchServices.applicationRegistered user info: {
    bundleIDs =     (
        "info.ocodo.CutBoxHelper"
    );
    isPlaceholder = 0;
}
```

Note I created the missing PlugIns directories listed and it had no difference.

This really sucks.  CutBox has been awesome and even the crashes were possible to workaround.

**Comment by jasonm23** [comment]
Thanks for the additional information.  It may be possible to overcome this.

It looks like a louder fail message concerning application signing.

So it may be possible to fix it.

I'm in the process of updating the libraries and updating to Swift 5, so I can rebuild. Hopefully this is fixable.

**Comment by jasonm23** [comment]
load code signature error

This is the breadcrumb we needed.

**Comment by jlongman** [comment]
As a note my old install of FlyCut still works.  (It's nowhere near as useful as CutBox though.)

**Comment by jasonm23** [comment]
Thank you for the information

>

**Comment by jasonm23** [comment]
Related to #95

**Comment by epetushk** [comment]
Cutbox is the only working alternative I could find after switching from Windows to Mac, and now this malware warning. Any chance it can be fixed?

**Comment by levjad** [comment]
Maybe this is helpful:

Notarized macOS builds
https://developer.apple.com/documentation/xcode/notarizing_macos_software_before_distribution

Saw that in the recent VSCode update.

**Comment by jasonm23** [comment]
related update note in #95

**Comment by jasonm23** [comment]
#95  - There is a pre-release ready for user testing.  

Works ok for me on Mojave. 

<img width="698" alt="Screenshot 2020-05-09 at 3 42 43 PM" src="https://user-images.githubusercontent.com/71587/81467570-12bf2100-920c-11ea-9de3-b91b7dfc6f73.png">

**Comment by jasonm23** [comment]
@levjad - BTW since I don't participate in the Apple Developer program I cannot notarise builds, but it seems to be ok without on a clean MacOS that's unrelated to the dev machine.  Hope 1.4.6 works for you.

**Comment by jasonm23** [comment]
1.4.7 pre-release is now available from the release page

**Comment by theofruitrouge** [comment]
I solves the problem on macOS Catalina 10.15.4 (MBP 15" 2019).

**Comment by jasonm23** [comment]
@theofruitrouge that's good news.  

I'll slice off a proper release and update the landing page.

**Comment by jasonm23** [comment]
# 1.4.8 official release now available

Sorry about the wait!

![Screenshot 2020-05-10 at 1 27 30 PM](https://user-images.githubusercontent.com/71587/81491535-22993c80-92c2-11ea-82c9-5fefc04dc15a.png)
![Screenshot 2020-05-10 at 1 26 50 PM](https://user-images.githubusercontent.com/71587/81491536-24fb9680-92c2-11ea-8519-33e0f100e7cc.png)

**Comment by hanan-simplee** [comment]
why me? :(

![image](https://user-images.githubusercontent.com/41114563/81498965-980c0980-92d0-11ea-9703-4892f1052916.png)

**Comment by jasonm23** [comment]
@theofruitrouge please post your Catalina about window to compare with @hanan-simplee 

Thank you.

**Comment by jasonm23** [comment]
Oh sorry folks, check this post to display build number of macos.

https://osxdaily.com/2015/03/23/find-build-number-os-x-mac/

**Comment by theofruitrouge** [comment]
Hi,
Sorry about the little delay.
Here it is :
<img width="589" alt="image" src="https://user-images.githubusercontent.com/21720326/81505776-1036f700-92f2-11ea-823f-d609252ac5d5.png">

**Comment by hanan-simplee** [comment]
This is mine. 10.15.4 (19E287) - so it does look the same.

**Comment by hanan-simplee** [comment]
Update: looks like it's working and even updated itself to 1.4.9
I'm not sure exactly what changed. I removed and downloaded again, and at some point saw that the "can't be open" message changed and had an "open" button... and it worked.

**Comment by jasonm23** [comment]
https://www.zdnet.com/article/apples-macos-catalina-libreoffice-users-still-get-scary-malware-messages/

As you will see above this is a problem on Apple side.

If the situation gets worse I will simply pull the binary releases altogether, and provide a brew style method of installation.  Giving users a compile and use their own binary option.
