### ISSUE TITLE
Unnecessary notification at startup

### ISSUE THREAD

**Issue by awreccan** [cutbox/CutBox#96]
I don't intend to use cutboxFunctions so it's quite annoying when CutBox sends this notification on startup.

![image](https://user-images.githubusercontent.com/10543509/81501215-a1659800-9309-11ea-890b-02f289fc22c1.png)

This is compounded by the fact that I have CutBox set to start on login, which is when a bunch of other start-at-login apps also spam notifications about updates etc, and having to swipe away CutBox's notification to get to the important ones becomes a minor pain point.

Editing .cutbox.js to return one empty function also causes an unnecessary notification to show up. There should be an option to turn off this notification and/or js support entirely.

**Comment by jasonm23** [comment]
@awreccan - thanks I will do that.

**Comment by jasonm23** [comment]
Switched off in 1.4.9

**Comment by awreccan** [comment]
Downloaded 1.4.9 but it's still happening.
![image](https://user-images.githubusercontent.com/10543509/81527424-ca7b3c80-938c-11ea-9d4b-de61bdf2d897.png)

**Comment by awreccan** [comment]
https://github.com/cutbox/CutBox/blob/1a0043e5974cdbf602d30fd75e88fb83a831f58f/CutBox/CutBox/Source/App/Services/JSFuncService.swift#L104-L111

This is what I was requesting: this entire if-else block should either be deleted or placed behind something like a `useJs` flag

**Comment by jasonm23** [comment]
@awreccan  That's error messaging specifically for that purpose and it's staying.  

You have an empty `~/.cutbox.js` because you were trying to stop the nag notification.  

To stop other messages: delete it.
