### ISSUE TITLE
Laggy search

### ISSUE THREAD

**Issue by awreccan** [cutbox/CutBox#98]
Search is quite laggy. Wondering if you could add a debounce to the searchbar? 

https://levelup.gitconnected.com/debounce-in-javascript-improve-your-applications-performance-5b01855e086

**Comment by jasonm23** [comment]
Thanks will have a look. Can you share how many items are in your history so I can do a test based on your situation,

**Comment by jasonm23** [comment]
Testing with 4k plus items it's fine.

**Comment by jasonm23** [comment]
note: I'll reopen this given some more info about conditions for lagging.

I think adding some automated performance tests would be useful.
